# Generated by nixos-generate-config on the target machine.
#
# DO NOT write this file by hand. On install day:
#   1. Boot the NixOS installer
#   2. Partition and mount your disks (see BUILD_PLAN.md Phase 2)
#   3. Run: nixos-generate-config --root /mnt
#   4. Copy /mnt/etc/nixos/hardware-configuration.nix here
#   5. Commit it before running nixos-install
#
# The generated file will contain:
#   - boot.initrd.availableKernelModules
#   - boot.initrd.luks.devices (if you used LUKS encryption)
#   - fileSystems mount points with UUIDs
#   - hardware.cpu.amd.updateMicrocode = true
#   - nixpkgs.hostPlatform
#
{ ... }: { }
